version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y java-11-openjdk-devel maven
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -DskipTests 
  post_build:
    commands:
      - echo Build completed on `date`
      - ls target/

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
